### PR TITLE
Added ReaDrum Machine

### PR DESCRIPTION
**Pull request by Suzuki-Re**
Added 
+ ReaDrum Machine layout script. 
+ Suzuki's repo check for JSFX which is necessary for ReaDrum Machine

### CODE REVIEW

**Comment by Suzuki-Re** [comment]
Hmm, adding my repo to ThirdPartyDeps function causes a problem (It attempts to install it even though it's already in the path), but it works in other scripts so I guess  something is wrong with implementation?

**Comment by BryanChi** [comment]
Thanks for implementing it into FX device, this is really exciting! 
Regarding the problem in ThirdPartyDeps, maybe you can ask Sexan about it? I read through the code and didn't find any apparent mistake. So I think only Sexan would know what's going on there because he wrote it.

**Comment by Suzuki-Re** [comment]
I will! Let me fix some typo/bugs while I'm at it.

**Comment by Suzuki-Re** [comment]
Sorry for being late. Resolved the said issue

**Comment by Suzuki-Re** [comment]
one sec

**Comment by Suzuki-Re** [comment]
OK, I double checked it

**Comment by BryanChi** [comment]
Thank you so much for this amazing work!!!

**Pull request merged**
